name: build
on:
  push:
    branches: 
      - master
    paths:
     - "**/*.go"
     - "go.mod"
     - "go.sum"
     - ".github/workflows/*.yml"
  create:
    tags:
      - "v*"

env:
  GO111MODULE: on

defaults:
  run:
    shell: bash

jobs:
  build:
    name: build testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set tag name
        run: echo "CURRENT_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
          
      - name: Build
        run: |
          ./build.sh
          zip btsniffer.zip btsniffer

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        if: ${{ startsWith(github.ref, 'refs/tags/v') }} 
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: btsniffer.zip
          asset_name: btsniffer-linux.zip
          tag: ${{ github.ref }}
          body: "${{ env.CURRENT_TAG }} is released"