name: build
on:
  push:
    branches: 
      - master

env:
  GO111MODULE: on

defaults:
  run:
    shell: bash

jobs:
  build:
    name: build testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
          
      - name: Build
        run: |
          ./build.sh